version: "3.8"

services: 

    redis:
        image: redis:6.0.9
        logging:
            driver: "none"
  
    trump:
        build: 
            context: ./demo
            dockerfile: dockerfile
        command: python -u /app/trump.py
 
        volumes:
            - ./demo:/app
        depends_on: 
            - redis
    macron:
        build: 
            context: ./demo
            dockerfile: dockerfile
        command: python -u /app/macron.py
  
        volumes:
            - ./demo:/app
        depends_on: 
            - redis
    trudeau:
        build: 
            context: ./demo
            dockerfile: dockerfile
        command: python -u /app/trudeau.py
  
        volumes:
            - ./demo:/app
        depends_on: 
            - redis
     